pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.home, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from pages.views import ClientViewSet
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

router =  routers.DefaultRouter()
router.register(r'clients', ClientViewSet)

urlpatterns = [
    # Django Admin
    path('admin/', admin.site.urls),
    # User Management
    path('accounts/', include('allauth.urls')),
    # Form
    path('', include('pages.urls', namespace='pages')),
    # API
    path('api/', include(router.urls)),
    # JWT
    path('token/', TokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
]

pages/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Client(models.Model):
    payment_id = models.IntegerField()
    start_date = models.DateField(max_length=8)
    end_date = models.DateField(max_length=8)
    original_value = models.FloatField()
    collaborator_owner = models.CharField(max_length=30)
    social_bussiness_name = models.CharField(max_length=40)
    CNPJ = models.CharField( max_length=14, validators=[MinLengthValidator(14)])

    def __int__(self):
        return self.payment_id

pages/forms.py
from django.forms import DateField, ModelForm, DateInput
from .models import Client
from project import settings
import requests
import json
from django.core.exceptions import ValidationError



class DateInput(DateInput):
    input_type = 'date'


class ClientForm(ModelForm):
    start_date = DateField(widget=DateInput, input_formats=settings.DATE_INPUT_FORMATS)
    end_date = DateField(widget=DateInput, input_formats=settings.DATE_INPUT_FORMATS)
    class Meta:
        widgets = {'my_date_field': DateInput()}
        model = Client
        fields = [
            "payment_id",
            "start_date",
            "end_date",
            "original_value",
            "collaborator_owner",
            "social_bussiness_name",
            "CNPJ",
            ]


    


pages/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from .forms import ClientForm
from rest_framework import viewsets
from pages.models import Client
from pages.api.serializer import ClientSerializer
from rest_framework.permissions import IsAuthenticated



class ClientViewSet(viewsets.ModelViewSet):
    permission_class = (IsAuthenticated, )
    
    queryset = Client.objects.all()
    serializer_class= ClientSerializer





    
class HomePageView(TemplateView):
    template_name = 'home.html'

    
    def home(request):

        form = ClientForm()
        
        if request.method == 'POST':
            form = ClientForm(request.POST)
            if form.is_valid():
                form.save()
          
                
        context = {'form':form}
        return render(request, 'home.html', context)






templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <style>
        #line{
            align-content: center;
        }
        #end {
            position: relative;
            height: 0%;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Sá Orçamentos</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastre-se</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
   
    {% load static %}
    <script src="{% static 'javascript.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Example{% endblock %}

{% block content %}
<div class="col-14 m-auto pt-4 pb-2">
    <div id="result"></div>
    <form name="form" id="form" method="post">
    {% csrf_token %}
    {% if user.is_authenticated %}
    <h2>Preencha o formulário com as informações do pagamento, para nossos colaboradores calcularem os juros caso necessário.</h2>
    <hr size="8" color="gray">
    <div class="form-group mt-4">Id do pagamento: <br> {{form.payment_id}}</div>
    <div class="form-group mt-4">Data de início do serviço (dd/mm/aaaa): <br> {{form.start_date}}</div>
    <div class="form-group mt-4">Data de término do serviço (dd/mm/aaaa): <br> {{form.end_date}}</div>
    <div class="form-group mt-4">Valor inicial cobrado pelo serviço: <br> {{form.original_value}}</div>
    <div class="form-group mt-4">Colaborador responsável: <br> {{form.collaborator_owner}}</div>
    <div class="form-group mt-4">Rasão social: <br> {{form.social_bussiness_name}}</div>
    <div class="form-group mt-4">CNPJ: <br> {{form.CNPJ}}</div>    
    <input class="btn btn-primary" type="submit" value="Enviar"></input>
    {% else %}
    <h1 >Olá cliente!</h1>
    <p id="line" style = "font-size: 25px">
    <br>
    Este site é destinado para a solicitação da extensão do prazo de entrega.
    <br>
    <br>
    Por gentileza, registre-se para ter acesso ao formulário de solicitação.
    <br>
    <br>
    Suas informações serão disponibilizadas em uma API pública, que pode ser acessada <a href="https://api-client-sa.herokuapp.com/api/clients/">clicando aqui</a>
    <br>
    <br>
    
    </p>
    {% endif %}
    </form> 
</div>


{% endblock %}